import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import TopNav from '../components/TopNav.tsx';

import { UserProvider } from '../contexts/UserContext.tsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Records",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <TopNav />
            <div className="container mx-auto p-4">
              {children}
            </div>
        </UserProvider>
      </body>
    </html>
  );
}
